services:
  postgres:
    image: postgres:latest
    container_name: app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_pgdata:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: app-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: app@app.com
      PGADMIN_DEFAULT_PASSWORD: app
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_pgdata:
  pgadmin_data:
